In [2]:
import numpy as np
import pandas as pd

### Column Headers
- Transaction unique identifier
- Date of Transfer
- Postcode
- Property Type (D=Detached, S = Semi-Detached, T = Terraced, F = Flats/Maisonettes, O = Other)
- Old/New (Y=Newly Built, N=an established residential building)
- Duration (F=Freehold, L=Leasehold)
- PAON (Primary Addressable Object Name)
- SAON (Secondary Addressable Object Name)
- Street
- Locality
- Town/City
- District
- County
- PPD Category Type (A = Standard Price Paid, B = Additional Price Paid)
- Record Status (A = Addition, C = Change, D = Delete)

In [6]:
headers = ["TID", "Date", "Postcode", "Prop. Type", "New?", "Duration", "PAON", "SAON", "Street", "Locality", "Town_City", "District", "County", "PPD", "Record_Status"]
df = pd.read_csv('data/pp-2017.csv', names=headers)

In [7]:
df.head()

,TID,Date,Postcode,Prop. Type,New?,Duration,PAON,SAON,Street,Locality,Town_City,District,County,PPD,Record_Status
{4C4EDFFF-6C65-1854-E050-A8C063054F34},325000,2017-02-17 00:00,SO50 9QN,T,Y,F,21,NaN,HAWKINS WAY,NaN,EASTLEIGH,EASTLEIGH,HAMPSHIRE,A,A
{4C4EDFFF-6C66-1854-E050-A8C063054F34},424950,2017-01-30 00:00,GU14 9FS,D,Y,F,14,NaN,DARTFORD RISE,NaN,FARNBOROUGH,RUSHMOOR,HAMPSHIRE,A,A
{4C4EDFFF-6C67-1854-E050-A8C063054F34},499950,2017-03-01 00:00,SO31 8LN,D,Y,F,50,NaN,CLEVERLEY RISE,BURSLEDON,SOUTHAMPTON,EASTLEIGH,HAMPSHIRE,A,A
{4C4EDFFF-6C68-1854-E050-A8C063054F34},410000,2017-03-06 00:00,GU14 8AG,T,N,F,12A,NaN,FARNBOROUGH STREET,NaN,FARNBOROUGH,RUSHMOOR,HAMPSHIRE,A,A
{4C4EDFFF-6C69-1854-E050-A8C063054F34},184500,2017-02-17 00:00,SO19 2DP,S,N,L,21,NaN,MANOR ROAD SOUTH,NaN,SOUTHAMPTON,SOUTHAMPTON,SOUTHAMPTON,A,A